In [1]:
import numpy as np #PAra algebra lineal
import pandas as pd #Procesamiento de datos
import matplotlib.pyplot as plt #Graficar
import seaborn as sns #Visualizar datos
from collections import Counter
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [2]:
dfTrain = pd.read_csv("train.csv")
dfTrain

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          1          60       RL         65.0     8450   Pave   NaN      Reg   
1          2          20       RL         80.0     9600   Pave   NaN      Reg   
2          3          60       RL         68.0    11250   Pave   NaN      IR1   
3          4          70       RL         60.0     9550   Pave   NaN      IR1   
4          5          60       RL         84.0    14260   Pave   NaN      IR1   
...      ...         ...      ...          ...      ...    ...   ...      ...   
1455    1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456    1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457    1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458    1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459    1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
dfTest = pd.read_csv("test.csv")
dfTest

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [4]:
labels = ['Cheap', 'Mid', 'Expensive']

dfTrain['SalePrice'] = pd.cut(dfTrain['SalePrice'], 3, labels=labels)

dfTrain

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          1          60       RL         65.0     8450   Pave   NaN      Reg   
1          2          20       RL         80.0     9600   Pave   NaN      Reg   
2          3          60       RL         68.0    11250   Pave   NaN      IR1   
3          4          70       RL         60.0     9550   Pave   NaN      IR1   
4          5          60       RL         84.0    14260   Pave   NaN      IR1   
...      ...         ...      ...          ...      ...    ...   ...      ...   
1455    1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456    1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457    1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458    1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459    1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal      Cheap  
1         5   2007        WD         Normal      Cheap  
2         9   2008        WD         Normal      Cheap  
3         2   2006        WD        Abnorml      Cheap  
4        12   2008        WD         Normal      Cheap  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal      Cheap  
1456      2   2010        WD         Normal      Cheap  
1457      5   2010        WD         Normal      Cheap  
1458      4   2010        WD         Normal      Cheap  
1459      6   2008        WD         Normal      Cheap  

[1460 rows x 81 columns]

In [5]:
mapping = {'Cheap': 1, 'Mid': 2, 'Expensive': 3}
dfTrain['SalePrice'] = dfTrain['SalePrice'].map(mapping)

In [6]:
df = pd.concat([dfTrain, dfTest], sort=False)
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1.0          60       RL         65.0     8450   Pave   NaN      Reg   
1        2.0          20       RL         80.0     9600   Pave   NaN      Reg   
2        3.0          60       RL         68.0    11250   Pave   NaN      IR1   
3        4.0          70       RL         60.0     9550   Pave   NaN      IR1   
4        5.0          60       RL         84.0    14260   Pave   NaN      IR1   
...      ...         ...      ...          ...      ...    ...   ...      ...   
1454     NaN         160       RM         21.0     1936   Pave   NaN      Reg   
1455     NaN         160       RM         21.0     1894   Pave   NaN      Reg   
1456     NaN          20       RL        160.0    20000   Pave   NaN      Reg   
1457     NaN          85       RL         62.0    10441   Pave   NaN      Reg   
1458     NaN          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolQC  Fence MiscFeature MiscVal MoSold  \
0            Lvl    AllPub  ...    NaN    NaN         NaN       0      2   
1            Lvl    AllPub  ...    NaN    NaN         NaN       0      5   
2            Lvl    AllPub  ...    NaN    NaN         NaN       0      9   
3            Lvl    AllPub  ...    NaN    NaN         NaN       0      2   
4            Lvl    AllPub  ...    NaN    NaN         NaN       0     12   
...          ...       ...  ...    ...    ...         ...     ...    ...   
1454         Lvl    AllPub  ...    NaN    NaN         NaN       0      6   
1455         Lvl    AllPub  ...    NaN    NaN         NaN       0      4   
1456         Lvl    AllPub  ...    NaN    NaN         NaN       0      9   
1457         Lvl    AllPub  ...    NaN  MnPrv        Shed     700      7   
1458         Lvl    AllPub  ...    NaN    NaN         NaN       0     11   

     YrSold SaleType  SaleCondition  SalePrice      Id  
0      2008       WD         Normal          1     NaN  
1      2007       WD         Normal          1     NaN  
2      2008       WD         Normal          1     NaN  
3      2006       WD        Abnorml          1     NaN  
4      2008       WD         Normal          1     NaN  
...     ...      ...            ...        ...     ...  
1454   2006       WD         Normal        NaN  2915.0  
1455   2006       WD        Abnorml        NaN  2916.0  
1456   2006       WD        Abnorml        NaN  2917.0  
1457   2006       WD         Normal        NaN  2918.0  
1458   2006       WD         Normal        NaN  2919.0  

[2919 rows x 82 columns]

In [7]:
dfNC = df.select_dtypes(include=['int64', 'float64']).columns

In [8]:
scaler = StandardScaler()
df[dfNC] = scaler.fit_transform(df[dfNC])

In [9]:
df

Id  MSSubClass MSZoning  LotFrontage   LotArea Street Alley  \
0    -1.730865    0.067331       RL    -0.184481 -0.217879   Pave   NaN   
1    -1.728492   -0.873616       RL     0.458190 -0.072044   Pave   NaN   
2    -1.726120    0.067331       RL    -0.055946  0.137197   Pave   NaN   
3    -1.723747    0.302568       RL    -0.398704 -0.078385   Pave   NaN   
4    -1.721374    0.067331       RL     0.629569  0.518903   Pave   NaN   
...        ...         ...      ...          ...       ...    ...   ...   
1454       NaN    2.419700       RM    -2.069648 -1.043937   Pave   NaN   
1455       NaN    2.419700       RM    -2.069648 -1.049263   Pave   NaN   
1456       NaN   -0.873616       RL     3.885767  1.246808   Pave   NaN   
1457       NaN    0.655424       RL    -0.313015  0.034605   Pave   NaN   
1458       NaN    0.067331       RL     0.201122 -0.068620   Pave   NaN   

     LotShape LandContour Utilities  ... PoolQC  Fence MiscFeature   MiscVal  \
0         Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
1         Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
2         IR1         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
3         IR1         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
4         IR1         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
...       ...         ...       ...  ...    ...    ...         ...       ...   
1454      Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
1455      Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
1456      Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   
1457      Reg         Lvl    AllPub  ...    NaN  MnPrv        Shed  1.144312   
1458      Reg         Lvl    AllPub  ...    NaN    NaN         NaN -0.089592   

        MoSold    YrSold SaleType  SaleCondition  SalePrice        Id  
0    -1.552184  0.157646       WD         Normal          1       NaN  
1    -0.446925 -0.602962       WD         Normal          1       NaN  
2     1.026753  0.157646       WD         Normal          1       NaN  
3    -1.552184 -1.363569       WD        Abnorml          1       NaN  
4     2.132012  0.157646       WD         Normal          1       NaN  
...        ...       ...      ...            ...        ...       ...  
1454 -0.078505 -1.363569       WD         Normal        NaN  1.721367  
1455 -0.815344 -1.363569       WD        Abnorml        NaN  1.723741  
1456  1.026753 -1.363569       WD        Abnorml        NaN  1.726115  
1457  0.289914 -1.363569       WD         Normal        NaN  1.728490  
1458  1.763592 -1.363569       WD         Normal        NaN  1.730864  

[2919 rows x 82 columns]

### X_train

In [10]:
qMapping = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1}
eMapping = {'Gd': 4, 'Av': 3, 'Mn': 2, 'No': 1}
fMapping = {'GLQ': 6, 'ALQ': 5, 'BLQ': 4, 'Rec': 3, 'LwQ': 2, 'Unf': 1}
gfMapping = {'Fin': 3, 'RFn': 2, 'Unf': 1}
pdMapping = {'Y': 3, 'P': 2, 'N': 1}
fpMapping = {"Ex":6,"Gd":5,"TA":4,"Fa":3,"Po":2,"NA":1}

oFeatures = {
    'ExterQual': qMapping, 'ExterCond': qMapping,
    'BsmtQual': qMapping, 'BsmtCond': qMapping,
    'BsmtFinType1': fMapping, 'BsmtFinType2': fMapping,
    'HeatingQC': qMapping,
    'KitchenQual': qMapping,
    'GarageFinish': gfMapping,
    'GarageQual': qMapping, 'GarageCond': qMapping,
    'PavedDrive': pdMapping,
    'FireplaceQu' : fpMapping
}

for f, m in oFeatures.items():
    df[f] = df[f].map(m)

nominals = [
    'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
    'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
    'MasVnrType', 'Foundation', 'Heating', 'CentralAir', 'Electrical', 'Functional', 'GarageType', 'SaleType'
]

dfEncoded = pd.get_dummies(df, columns=nominals, drop_first=True)

In [11]:
dfEncoded.shape

(2919, 199)

In [12]:
for i in dfEncoded.columns:
    if dfEncoded[i].dtypes == "object":
        print(i)

Alley
RoofStyle
BsmtExposure
PoolQC
Fence
MiscFeature
SaleCondition


In [13]:
dfEncoded.drop([
    "Alley","PoolQC","Fence","MiscFeature","OverallCond","Id",
    "MiscVal","YrSold","3SsnPorch","LowQualFinSF","SaleCondition",
    "RoofStyle","BsmtUnfSF","BsmtFinSF1","BsmtFinSF2","BsmtExposure"
],axis=1,inplace=True)

In [14]:
dfEncoded.dropna(inplace=True)

In [21]:
X = dfEncoded.drop('SalePrice', axis = 1)
y = dfEncoded["SalePrice"]

In [22]:
X

Id  MSSubClass  LotFrontage   LotArea  OverallQual  YearBuilt  \
1    -1.728492   -0.873616     0.458190 -0.072044    -0.063185   0.154764   
2    -1.726120    0.067331    -0.055946  0.137197     0.646183   0.980221   
3    -1.723747    0.302568    -0.398704 -0.078385     0.646183  -1.859351   
4    -1.721374    0.067331     0.629569  0.518903     1.355551   0.947203   
6    -1.716629   -0.873616     0.243967 -0.010667     1.355551   1.079276   
...        ...         ...          ...       ...          ...        ...   
1447  1.702393    0.067331     0.458190 -0.021319     1.355551   0.782111   
1451  1.711883   -0.873616     0.372501 -0.114907     1.355551   1.211349   
1455  1.721374    0.067331    -0.313015 -0.285470    -0.063185   0.914184   
1456  1.723747   -0.873616     0.672414  0.381311    -0.063185   0.220801   
1457  1.726120    0.302568    -0.141636 -0.142806     0.646183  -1.000876   

      YearRemodAdd  MasVnrArea  ExterQual  ExterCond  ...  GarageType_CarPort  \
1        -0.395604   -0.569991          3          3  ...               False   
2         0.848965    0.333506          4          3  ...               False   
3        -0.682812   -0.569991          3          3  ...               False   
4         0.753229    1.382009          4          3  ...               False   
6         0.992569    0.467357          4          3  ...               False   
...            ...         ...        ...        ...  ...                 ...   
1447      0.561757    1.872797          4          3  ...               False   
1451      1.184041    0.511974          4          3  ...               False   
1455      0.753229   -0.569991          3          3  ...               False   
1456      0.178812    0.093689          3          3  ...               False   
1457      1.040437   -0.569991          5          4  ...               False   

      GarageType_Detchd  SaleType_CWD  SaleType_Con  SaleType_ConLD  \
1                 False         False         False           False   
2                 False         False         False           False   
3                  True         False         False           False   
4                 False         False         False           False   
6                 False         False         False           False   
...                 ...           ...           ...             ...   
1447              False         False         False           False   
1451              False         False         False           False   
1455              False         False         False           False   
1456              False         False         False           False   
1457              False         False         False           False   

      SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  
1              False           False         False         False         True  
2              False           False         False         False         True  
3              False           False         False         False         True  
4              False           False         False         False         True  
6              False           False         False         False         True  
...              ...             ...           ...           ...          ...  
1447           False           False         False         False         True  
1451           False           False          True         False        False  
1455           False           False         False         False         True  
1456           False           False         False         False         True  
1457           False           False         False         False         True  

[584 rows x 182 columns]

In [23]:
y

1       1
2       1
3       1
4       1
6       2
       ..
1447    1
1451    2
1455    1
1456    1
1457    1
Name: SalePrice, Length: 584, dtype: category
Categories (3, int64): [1 < 2 < 3]

In [24]:
X.isnull().sum()

    Id            0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
                 ..
SaleType_ConLI    0
SaleType_ConLw    0
SaleType_New      0
SaleType_Oth      0
SaleType_WD       0
Length: 182, dtype: int64

In [25]:
y.isnull().sum()

0

In [26]:
print(X[X.isnull().any(axis=1)])

Empty DataFrame
Columns: [    Id, MSSubClass, LotFrontage, LotArea, OverallQual, YearBuilt, YearRemodAdd, MasVnrArea, ExterQual, ExterCond, BsmtQual, BsmtCond, BsmtFinType1, BsmtFinType2, TotalBsmtSF, HeatingQC, 1stFlrSF, 2ndFlrSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Fireplaces, FireplaceQu, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, ScreenPorch, PoolArea, MoSold, MSZoning_FV, MSZoning_RH, MSZoning_RL, MSZoning_RM, Street_Pave, LotShape_IR2, LotShape_IR3, LotShape_Reg, LandContour_HLS, LandContour_Low, LandContour_Lvl, Utilities_NoSeWa, LotConfig_CulDSac, LotConfig_FR2, LotConfig_FR3, LotConfig_Inside, LandSlope_Mod, LandSlope_Sev, Neighborhood_Blueste, Neighborhood_BrDale, Neighborhood_BrkSide, Neighborhood_ClearCr, Neighborhood_CollgCr, Neighborhood_Crawfor, Neighborhood_Edwards, Neighborhood_Gilbert, Neighborhood_IDOTRR, Ne

## 3. Dividimos la data en entrenamiento y prueba

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 4. Escalar la data

In [28]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

array([[-0.09659708, -0.06729793,  0.01879366, ...,  0.        ,
         0.        ,  0.07703376],
       [ 0.06975112, -0.01361664, -0.03233374, ...,  0.        ,
         0.        ,  0.0810971 ],
       [-0.03566745,  0.00476314,  0.02938222, ...,  0.        ,
         0.        ,  0.07074166],
       ...,
       [-0.01415643,  0.02490011, -0.03281169, ...,  0.        ,
         0.        ,  0.08229584],
       [ 0.05576821,  0.09668196, -0.09049561, ...,  0.        ,
         0.        ,  0.06538075],
       [-0.07052301, -0.04111497,  0.00467503, ...,  0.        ,
         0.        ,  0.06440525]])

In [29]:
X_test_scaled

array([[ 0.04048523, -0.06791173,  0.02895684, ...,  0.        ,
         0.        ,  0.07773636],
       [ 0.055816  , -0.06313795,  0.1074296 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.08004365, -0.06082972,  0.03190369, ...,  0.        ,
         0.        ,  0.06962981],
       ...,
       [-0.05827331,  0.00527487,  0.01575627, ...,  0.        ,
         0.        ,  0.07834193],
       [ 0.11530844,  0.00487298, -0.02265384, ...,  0.        ,
         0.        ,  0.0723731 ],
       [ 0.03142721,  0.00552221,  0.00243938, ...,  0.        ,
         0.        ,  0.08201541]])

## 5. Entrenamos el modelo

In [30]:
# Entrenar un modelo de SVM
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

## 6. Predecimos sobre la data

In [31]:
y_pred = svm_model.predict(X_test_scaled)

## 7. Evaluamos el modelo

In [32]:
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [33]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.8974358974358975
Confusion Matrix:
[[91  4  0]
 [ 7 14  0]
 [ 0  1  0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.93      0.96      0.94        95
           2       0.74      0.67      0.70        21
           3       0.00      0.00      0.00         1

    accuracy                           0.90       117
   macro avg       0.56      0.54      0.55       117
weighted avg       0.89      0.90      0.89       117



## 8. Tuneo de hiper-parámetros

In [34]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [35]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf']
}

### Inicializamos el modelo

In [36]:
svm_model = SVC(random_state=42)

In [37]:
grid_search = GridSearchCV(estimator=svm_model, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1)
#cv es el número de divisiones para la validación cruzada. 
#(5-fold cross-validation) en este caso.
#verbose toma valores booleanos o enteros. Inidica si se mostrara mensajes durante la corrida del modelo.
grid_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy', verbose=1)

### Obtenemos los mejores parámetros

In [38]:
best_params = grid_search.best_params_
print("Mejores hiperparámetros encontrados:", best_params)

Mejores hiperparámetros encontrados: {'C': 10, 'gamma': 0.1, 'kernel': 'linear'}


### Entrenamos el modelo con los mejores hiperparámetros

In [39]:
best_svm_model = SVC(**best_params, random_state=42)
#** desempaqueta un diccionario

#SVC(C=0.1, gamma=0.1, kernel='linear', random_state=42)
best_svm_model.fit(X_train_scaled, y_train)

SVC(C=10, gamma=0.1, kernel='linear', random_state=42)

### Predecimos

In [40]:
y_pred = best_svm_model.predict(X_test_scaled)

### Evaluamos el rendimiento del modelo

In [41]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [42]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.905982905982906
Confusion Matrix:
[[91  4  0]
 [ 6 15  0]
 [ 0  1  0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.94      0.96      0.95        95
           2       0.75      0.71      0.73        21
           3       0.00      0.00      0.00         1

    accuracy                           0.91       117
   macro avg       0.56      0.56      0.56       117
weighted avg       0.90      0.91      0.90       117

