In [78]:
import numpy as np #PAra algebra lineal
import pandas as pd #Procesamiento de datos
import matplotlib.pyplot as plt #Graficar
import seaborn as sns #Visualizar datos
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer


In [79]:
df = pd.read_csv("train.csv")

# Especifica las columnas que deseas eliminar
columns_to_drop = ['PoolQC', 'Fence','MiscFeature', 'Alley' ]

# Eliminar las columnas especificadas
df = df.drop(df.columns[0], axis=1)
df = df.drop(columns=columns_to_drop, axis=1)
df = df.dropna()


In [80]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
2           60       RL         68.0    11250   Pave      IR1         Lvl   
4           60       RL         84.0    14260   Pave      IR1         Lvl   
6           20       RL         75.0    10084   Pave      Reg         Lvl   
11          60       RL         85.0    11924   Pave      IR1         Lvl   
13          20       RL         91.0    10652   Pave      IR1         Lvl   

   Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
2     AllPub    Inside       Gtl  ...             0         0           0   
4     AllPub       FR2       Gtl  ...             0         0           0   
6     AllPub    Inside       Gtl  ...             0         0           0   
11    AllPub    Inside       Gtl  ...             0         0           0   
13    AllPub    Inside       Gtl  ...             0         0           0   

   PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
2         0       0       9    2008        WD         Normal    223500  
4         0       0      12    2008        WD         Normal    250000  
6         0       0       8    2007        WD         Normal    307000  
11        0       0       7    2006       New        Partial    345000  
13        0       0       8    2007       New        Partial    279500  

[5 rows x 76 columns]

In [81]:
df.tail()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
1439          60       RL         80.0    11584   Pave      Reg         Lvl   
1442          60       FV         85.0    11003   Pave      Reg         Lvl   
1447          60       RL         80.0    10000   Pave      Reg         Lvl   
1451          20       RL         78.0     9262   Pave      Reg         Lvl   
1456          20       RL         85.0    13175   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
1439    AllPub    Inside       Gtl  ...           216         0           0   
1442    AllPub    Inside       Gtl  ...             0         0           0   
1447    AllPub    Inside       Gtl  ...             0         0           0   
1451    AllPub    Inside       Gtl  ...             0         0           0   
1456    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
1439        0       0      11    2007        WD         Normal    197000  
1442        0       0       4    2009        WD         Normal    310000  
1447        0       0      12    2007        WD         Normal    240000  
1451        0       0       5    2009       New        Partial    287090  
1456        0       0       2    2010        WD         Normal    210000  

[5 rows x 76 columns]

In [82]:
# Inicializar el codificador de etiquetas
label_encoder = LabelEncoder()

# Iterar sobre cada columna del DataFrame
for column in df.columns:
    # Verificar si la columna es de tipo 'object' (es decir, una columna categórica)
    if df[column].dtype == 'object':
        # Aplicar Label Encoding solo a las columnas categóricas
        df[column] = label_encoder.fit_transform(df[column])

In [83]:
# Convertir todos los datos a tipo float
df = df.astype(float)


In [84]:
X = df.drop('SalePrice', axis = 1)
y = df["SalePrice"]



In [85]:
X.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 75, dtype: int64

In [86]:
y.isnull().sum()

0

In [87]:
print(X[X.isnull().any(axis=1)])


Empty DataFrame
Columns: [MSSubClass, MSZoning, LotFrontage, LotArea, Street, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MiscVal, MoSold, YrSold, SaleType, SaleCondition]
Index: []

[0 rows x 75 columns]


# 3. Dividimos la data en entrenamiento y prueba

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 4. Escalar la data

In [89]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Entrenamos el modelo

In [112]:
# Entrenar un modelo de SVM
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

# 6. Predecimos sobre la data

In [113]:
y_pred = svm_model.predict(X_test_scaled)

# 7. Evaluamos el modelo

In [114]:
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, zero_division=1)

In [115]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.016666666666666666
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

     82500.0       0.00      1.00      0.00         0
    134450.0       1.00      0.00      0.00         1
    140000.0       1.00      0.00      0.00         1
    143500.0       0.00      1.00      0.00         0
    148000.0       1.00      0.00      0.00         1
    149900.0       0.00      1.00      0.00         0
    151000.0       1.00      0.00      0.00         1
    155000.0       0.00      1.00      0.00         0
    157000.0       0.00      1.00      0.00         0
    160000.0       0.00      1.00      0.00         0
    160200.0       1.00      0.00      0.00         1
    164500.0       0.00      1.00      0.00         0
    164900.0       1.00      0.00      0.00         1
    165000.0       0.00      1.00      0.00        

# 8. Tuneo de Hiper-Parametros

### Importamos la libreria necesaria

In [94]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [95]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf']
}

### Inicializamos el modelo

In [97]:
svm_model = SVC(random_state=42)

In [98]:
grid_search = GridSearchCV(estimator=svm_model, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1)
#cv es el número de divisiones para la validación cruzada. 
#(5-fold cross-validation) en este caso.
#verbose toma valores booleanos o enteros. Inidica si se mostrara mensajes durante la corrida del modelo.
grid_search.fit(X_train_scaled, y_train)


Fitting 5 folds for each of 24 candidates, totalling 120 fits


c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy', verbose=1)

### Obtenemos los mejores parametros

In [99]:
best_params = grid_search.best_params_
print("Mejores hiperparámetros encontrados:", best_params)

Mejores hiperparámetros encontrados: {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}


### Entrenamos el modelo con los mejores hiperparámetros

In [100]:
best_svm_model = SVC(**best_params, random_state=42)
#** desempaqueta un diccionario

#SVC(C=0.1, gamma=0.1, kernel='linear', random_state=42)
best_svm_model.fit(X_train_scaled, y_train)

SVC(C=1, gamma=0.01, random_state=42)

### Predecimos

In [101]:
y_pred = best_svm_model.predict(X_test_scaled)

### Evaluamos el rendimiento del modelo

In [107]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, zero_division=1)


In [108]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.0
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

    134450.0       1.00      0.00      0.00       1.0
    140000.0       1.00      0.00      0.00       1.0
    148000.0       1.00      0.00      0.00       1.0
    151000.0       1.00      0.00      0.00       1.0
    155000.0       0.00      1.00      0.00       0.0
    160200.0       1.00      0.00      0.00       1.0
    164900.0       1.00      0.00      0.00       1.0
    169500.0       1.00      0.00      0.00       1.0
    170000.0       1.00      0.00      0.00       1.0
    172500.0       1.00      0.00      0.00       1.0
    174000.0       1.00      0.00      0.00       1.0
    175000.0       1.00      0.00      0.00       1.0
    175500.0       1.00      0.00      0.00       1.0
    176000.0       1.00      0.00      0.00       2.0
    179900.0  