In [72]:
import numpy as np #PAra algebra lineal
import pandas as pd #Procesamiento de datos
import matplotlib.pyplot as plt #Graficar
import seaborn as sns #Visualizar datos
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer


In [192]:
df = pd.read_csv("train.csv")

# Especifica las columnas que deseas eliminar
columns_to_drop = ['PoolQC', 'Fence','MiscFeature', 'Alley', 'MiscVal' ]

# Eliminar las columnas especificadas
df = df.drop(df.columns[0], axis=1)
df = df.drop(columns=columns_to_drop, axis=1)
df = df.dropna()


In [193]:
# Obtener las columnas categóricas
categorical_columns = df.select_dtypes(include=['object']).columns

# Iterar sobre las columnas categóricas
for column in categorical_columns:
    # Obtener los valores únicos de la columna
    unique_values = df[column].unique()
    # Imprimir el nombre de la columna y sus valores únicos
    print(f"Valores únicos en la columna '{column}': {unique_values}")


Valores únicos en la columna 'MSZoning': ['RL' 'FV' 'RM']
Valores únicos en la columna 'Street': ['Pave' 'Grvl']
Valores únicos en la columna 'LotShape': ['IR1' 'Reg' 'IR2' 'IR3']
Valores únicos en la columna 'LandContour': ['Lvl' 'HLS' 'Bnk' 'Low']
Valores únicos en la columna 'Utilities': ['AllPub']
Valores únicos en la columna 'LotConfig': ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
Valores únicos en la columna 'LandSlope': ['Gtl' 'Mod' 'Sev']
Valores únicos en la columna 'Neighborhood': ['CollgCr' 'NoRidge' 'Somerst' 'NridgHt' 'NAmes' 'StoneBr' 'Gilbert'
 'SawyerW' 'NWAmes' 'Timber' 'ClearCr' 'Blmngtn' 'BrDale' 'Crawfor'
 'Sawyer' 'Edwards' 'SWISU' 'Veenker' 'Mitchel' 'OldTown']
Valores únicos en la columna 'Condition1': ['Norm' 'PosN' 'Feedr' 'Artery' 'RRAn' 'RRNn']
Valores únicos en la columna 'Condition2': ['Norm' 'PosN']
Valores únicos en la columna 'BldgType': ['1Fam' 'TwnhsE' 'Duplex' 'Twnhs' '2fmCon']
Valores únicos en la columna 'HouseStyle': ['2Story' '1Story' 'SFoyer' 'SLvl

In [194]:
from sklearn.preprocessing import LabelEncoder

# Crear una instancia de LabelEncoder
label_encoder = LabelEncoder()

# Lista de columnas categóricas
categorical_columns = ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 
                       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 
                       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 
                       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 
                       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 
                       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 
                       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 
                       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 
                       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 
                       'SaleType', 'SaleCondition', 'YrSold','MSSubClass']

# Iterar sobre las columnas categóricas y codificar sus valores
for column in categorical_columns:
    # Ajustar y transformar la columna actual
    df[column] = label_encoder.fit_transform(df[column])

# Verificar los cambios
print(df.head())


    MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  LandContour  \
2            3         1         68.0    11250       1         0            3   
4            3         1         84.0    14260       1         0            3   
6            0         1         75.0    10084       1         3            3   
11           3         1         85.0    11924       1         0            3   
13           0         1         91.0    10652       1         0            3   

    Utilities  LotConfig  LandSlope  ...  OpenPorchSF  EnclosedPorch  \
2           0          4          0  ...           42              0   
4           0          2          0  ...           84              0   
6           0          4          0  ...           57              0   
11          0          4          0  ...           21              0   
13          0          4          0  ...           33              0   

    3SsnPorch  ScreenPorch  PoolArea  MoSold  YrSold  SaleType  SaleCondition  \

In [195]:
df.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  LandContour  \
2            3         1         68.0    11250       1         0            3   
4            3         1         84.0    14260       1         0            3   
6            0         1         75.0    10084       1         3            3   
11           3         1         85.0    11924       1         0            3   
13           0         1         91.0    10652       1         0            3   

    Utilities  LotConfig  LandSlope  ...  OpenPorchSF  EnclosedPorch  \
2           0          4          0  ...           42              0   
4           0          2          0  ...           84              0   
6           0          4          0  ...           57              0   
11          0          4          0  ...           21              0   
13          0          4          0  ...           33              0   

    3SsnPorch  ScreenPorch  PoolArea  MoSold  YrSold  SaleType  SaleCondition  \
2           0            0         0       9       2         5              3   
4           0            0         0      12       2         5              3   
6           0            0         0       8       1         5              3   
11          0            0         0       7       0         4              4   
13          0            0         0       8       1         4              4   

    SalePrice  
2      223500  
4      250000  
6      307000  
11     345000  
13     279500  

[5 rows x 75 columns]

In [196]:
df.tail()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
1439           3         1         80.0    11584       1         3   
1442           3         0         85.0    11003       1         3   
1447           3         1         80.0    10000       1         3   
1451           0         1         78.0     9262       1         3   
1456           0         1         85.0    13175       1         3   

      LandContour  Utilities  LotConfig  LandSlope  ...  OpenPorchSF  \
1439            3          0          4          0  ...           88   
1442            3          0          4          0  ...           52   
1447            3          0          4          0  ...           65   
1451            3          0          4          0  ...           36   
1456            3          0          4          0  ...            0   

      EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MoSold  YrSold  \
1439            216          0            0         0      11       1   
1442              0          0            0         0       4       3   
1447              0          0            0         0      12       1   
1451              0          0            0         0       5       3   
1456              0          0            0         0       2       4   

      SaleType  SaleCondition  SalePrice  
1439         5              3     197000  
1442         5              3     310000  
1447         5              3     240000  
1451         4              4     287090  
1456         5              3     210000  

[5 rows x 75 columns]

In [197]:
# Convertir todos los datos a tipo float
df = df.astype(int)


In [198]:
X = df.drop('SalePrice', axis = 1)
y = df["SalePrice"]

X


MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
2              3         1           68    11250       1         0   
4              3         1           84    14260       1         0   
6              0         1           75    10084       1         3   
11             3         1           85    11924       1         0   
13             0         1           91    10652       1         0   
...          ...       ...          ...      ...     ...       ...   
1439           3         1           80    11584       1         3   
1442           3         0           85    11003       1         3   
1447           3         1           80    10000       1         3   
1451           0         1           78     9262       1         3   
1456           0         1           85    13175       1         3   

      LandContour  Utilities  LotConfig  LandSlope  ...  WoodDeckSF  \
2               3          0          4          0  ...           0   
4               3          0          2          0  ...         192   
6               3          0          4          0  ...         255   
11              3          0          4          0  ...         147   
13              3          0          4          0  ...         160   
...           ...        ...        ...        ...  ...         ...   
1439            3          0          4          0  ...           0   
1442            3          0          4          0  ...         168   
1447            3          0          4          0  ...           0   
1451            3          0          4          0  ...           0   
1456            3          0          4          0  ...         349   

      OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MoSold  \
2              42              0          0            0         0       9   
4              84              0          0            0         0      12   
6              57              0          0            0         0       8   
11             21              0          0            0         0       7   
13             33              0          0            0         0       8   
...           ...            ...        ...          ...       ...     ...   
1439           88            216          0            0         0      11   
1442           52              0          0            0         0       4   
1447           65              0          0            0         0      12   
1451           36              0          0            0         0       5   
1456            0              0          0            0         0       2   

      YrSold  SaleType  SaleCondition  
2          2         5              3  
4          2         5              3  
6          1         5              3  
11         0         4              4  
13         1         4              4  
...      ...       ...            ...  
1439       1         5              3  
1442       3         5              3  
1447       1         5              3  
1451       3         4              4  
1456       4         5              3  

[299 rows x 74 columns]

In [199]:
y

2       223500
4       250000
6       307000
11      345000
13      279500
         ...  
1439    197000
1442    310000
1447    240000
1451    287090
1456    210000
Name: SalePrice, Length: 299, dtype: int32

In [200]:
X.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
                ..
PoolArea         0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 74, dtype: int64

In [201]:
y.isnull().sum()

0

In [202]:
print(X[X.isnull().any(axis=1)])


Empty DataFrame
Columns: [MSSubClass, MSZoning, LotFrontage, LotArea, Street, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MoSold, YrSold, SaleType, SaleCondition]
Index: []

[0 rows x 74 columns]


# 3. Dividimos la data en entrenamiento y prueba

In [203]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 4. Escalar la data

In [220]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

array([[0.00000000e+00, 9.12434134e-05, 6.84325600e-03, ...,
        1.82486827e-04, 4.56217067e-04, 2.73730240e-04],
       [0.00000000e+00, 7.89284782e-05, 6.31427826e-03, ...,
        1.57856956e-04, 3.94642391e-04, 2.36785435e-04],
       [2.93271225e-04, 9.77570749e-05, 7.33178062e-03, ...,
        2.93271225e-04, 4.88785375e-04, 2.93271225e-04],
       ...,
       [2.01480898e-04, 6.71602992e-05, 7.05183142e-03, ...,
        6.71602992e-05, 3.35801496e-04, 2.01480898e-04],
       [0.00000000e+00, 9.01527934e-05, 7.66298744e-03, ...,
        9.01527934e-05, 4.50763967e-04, 2.70458380e-04],
       [3.87720734e-04, 9.69301835e-05, 7.65748449e-03, ...,
        9.69301835e-05, 4.84650917e-04, 2.90790550e-04]])

In [221]:
X_test_scaled

array([[0.00000000e+00, 6.38145541e-05, 2.68021127e-03, ...,
        1.91443662e-04, 3.19072771e-04, 1.91443662e-04],
       [0.00000000e+00, 7.12017943e-05, 7.68979378e-03, ...,
        2.13605383e-04, 3.56008972e-04, 2.13605383e-04],
       [0.00000000e+00, 8.60645326e-05, 5.07780742e-03, ...,
        3.44258130e-04, 4.30322663e-04, 2.58193598e-04],
       ...,
       [0.00000000e+00, 7.84798264e-05, 8.24038177e-03, ...,
        3.13919306e-04, 0.00000000e+00, 2.35439479e-04],
       [2.81616616e-04, 9.38722052e-05, 7.50977642e-03, ...,
        9.38722052e-05, 4.69361026e-04, 2.81616616e-04],
       [5.34991011e-04, 1.06998202e-04, 9.41584179e-03, ...,
        0.00000000e+00, 5.34991011e-04, 3.20994607e-04]])

# 5. Entrenamos el modelo

In [222]:
# Entrenar un modelo de SVM
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

# 6. Predecimos sobre la data

In [223]:
y_pred = svm_model.predict(X_test_scaled)

# 7. Evaluamos el modelo

In [224]:
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [225]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.0
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

      134450       0.00      0.00      0.00       1.0
      140000       0.00      0.00      0.00       1.0
      148000       0.00      0.00      0.00       1.0
      151000       0.00      0.00      0.00       1.0
      160200       0.00      0.00      0.00       1.0
      164900       0.00      0.00      0.00       1.0
      169500       0.00      0.00      0.00       1.0
      170000       0.00      0.00      0.00       1.0
      172500       0.00      0.00      0.00       1.0
      174000       0.00      0.00      0.00       1.0
      175000       0.00      0.00      0.00       1.0
      175500       0.00      0.00      0.00       1.0
      176000       0.00      0.00      0.00       2.0
      179900       0.00      0.00      0.00       1.0
      186700  

# 8. Tuneo de Hiper-Parametros

### Importamos la libreria necesaria

In [226]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [227]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf']
}

### Inicializamos el modelo

In [228]:
svm_model = SVC(random_state=42)

In [229]:
grid_search = GridSearchCV(estimator=svm_model, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1)
#cv es el número de divisiones para la validación cruzada. 
#(5-fold cross-validation) en este caso.
#verbose toma valores booleanos o enteros. Inidica si se mostrara mensajes durante la corrida del modelo.
grid_search.fit(X_train_scaled, y_train)


c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


Fitting 5 folds for each of 24 candidates, totalling 120 fits


GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy', verbose=1)

### Obtenemos los mejores parametros

In [230]:
best_params = grid_search.best_params_
print("Mejores hiperparámetros encontrados:", best_params)

Mejores hiperparámetros encontrados: {'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}


### Entrenamos el modelo con los mejores hiperparámetros

In [231]:
best_svm_model = SVC(**best_params, random_state=42)
#** desempaqueta un diccionario

#SVC(C=0.1, gamma=0.1, kernel='linear', random_state=42)
best_svm_model.fit(X_train_scaled, y_train)

SVC(C=0.1, gamma=0.1, kernel='linear', random_state=42)

### Predecimos

In [232]:
y_pred = best_svm_model.predict(X_test_scaled)

### Evaluamos el rendimiento del modelo

In [233]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\josea\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [234]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.0
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

      134450       0.00      0.00      0.00       1.0
      140000       0.00      0.00      0.00       1.0
      148000       0.00      0.00      0.00       1.0
      151000       0.00      0.00      0.00       1.0
      160200       0.00      0.00      0.00       1.0
      164900       0.00      0.00      0.00       1.0
      169500       0.00      0.00      0.00       1.0
      170000       0.00      0.00      0.00       1.0
      172500       0.00      0.00      0.00       1.0
      174000       0.00      0.00      0.00       1.0
      175000       0.00      0.00      0.00       1.0
      175500       0.00      0.00      0.00       1.0
      176000       0.00      0.00      0.00       2.0
      179900       0.00      0.00      0.00       1.0
      186700  